name: Snapshot Deletion Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  cleanup_old_snapshot:

    runs-on: ubuntu-latest

    env:
      SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      LEAD_EMAIL: ${{ secrets.LEAD_EMAIL }}
      THRESHOLD_MINUTES: ${{ secrets.THRESHOLD_MINUTES }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Packages
        run: pip install -r requirements.txt

      - name: Run Snapshot Cleanup
        run: python main.py